### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by rbruggner** [nolanlab/Rclusterpp#1]
From Brian Ripley:

"But there is still the allocation problem shown by AddressSanitizer (see Writing R Extensions)

 ### Name: Rclusterpp.hclust
 ### Title: Hierarchical Clustering
 ### Aliases: Rclusterpp.hclust

 ### ** Examples

 h <- Rclusterpp.hclust(USArrests, method="ward", distance="euclidean")
 =================================================================
 ==17367== ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x0000033e5560

   #0 0x7f9f9a7f9aca in operator delete(void*) _asan_rtl_
   #1 0x7f9f9d786dee in __gnu_cxx::new_allocator<int>::deallocate(int*, unsigned long) /usr/local/gcc48x/include/c++/4.8.2/ext/new_allocator.h:110
   #2 0x47af48 in do_dotcall /data/gannet/ripley/R/svn/R-devel/src/main/dotcode.c:597

which seems to indicate a problem when leaving."

**Comment by rbruggner** [comment]
I think this got fixed.
